### ISSUE TITLE
I want you to improve it

### ISSUE THREAD

**Issue by jellyhani** [tGecko/ChampSelectSpy#1]
Minimize windows
Top Fastening Release
Add a comma next to the nickname

**Comment by tGecko** [comment]
> Minimize windows
Do you mean minimize the window when the game starts?

> Top Fastening Release
I don't understand this

> Add a comma next to the nickname
why?

**Comment by jellyhani** [comment]
Do you mean minimize the window when the game starts?
yes 

Top Fastening Release
I play games in borderless window mode.
Because of that, it's uncomfortable to cover the game screen

Add a comma next to the nickname
It was just a small wish On second thought, I think it's okay not to do it

**Comment by ZenMaxe** [comment]
> Do you mean minimize the window when the game starts? yes
> 
> Top Fastening Release I play games in borderless window mode. Because of that, it's uncomfortable to cover the game screen
> 
> Add a comma next to the nickname It was just a small wish On second thought, I think it's okay not to do it

I Can Update This For You , If You Want

**Comment by tGecko** [comment]
I was just working on it :)

Pull requests are open, if you want to add anything.

Version 1.4: Added toggle to disable "always on top", added automatic minimizing on game start
