### ISSUE TITLE
Missing or incorrect names

### ISSUE THREAD

**Issue by cubedsphered** [tGecko/ChampSelectSpy#2]
I've noticed many of the lobbies I'm in, the tool detects 4 names (1 missing) or displays the incorrect name. I'm thinking this might be because of the code picking up Riot ID instead of Summoner ID/Name. Works as intended for majority of players, this is the exclusion. well done

**Comment by cubedsphered** [comment]
I should mention, in most cases, the player will have Riot ID same as Summoner Name, however, many Valorant players will have changed their Riot ID to something different than their League name.

**Comment by tGecko** [comment]
Kindly test [Release 1.3](https://github.com/tGecko/ChampSelectSpy/releases/tag/1.3).
If you could report back it'd help me very much.

**Comment by tGecko** [comment]
Thank you very much for your feedback.

**Comment by cubedsphered** [comment]
I've tested it using multiple lobbies, it works 100% of the time now

**Comment by tGecko** [comment]
Thanks a lot for reporting the issue and the feedback @cubedsphered !

**Comment by IthielMS** [comment]
I've getting a trouble with the app, never worked to me in too many lobbies, i dont have idea of what can be, but dont show up names and dont appear the Summoner and Gamestate, just dont work. Can u help me?

**Comment by cubedsphered** [comment]
> 

This is a separate issue; please file under new issue.
