### ISSUE TITLE
Malware detection in some antivirus programs

### ISSUE THREAD

**Issue by MrBlasyMSK** [tGecko/ChampSelectSpy#3]
Hello, the tool seems to me a very good idea although I have not tried it yet because before installing something I always do a scan with VirusTotal to make sure what I install.
Apparently this program is detected by 16/71 [VirusTotal](https://www.virustotal.com/gui/file/a62ed3b887993e708bf353cd5f2719262d1d02474be37cf015fc78992c1e997c/detection) antivirus as a dangerous file. Is there any way to make it so that there are not so many or can you explain something about the code and why it detects it as a virus? Thanks in advance

**Comment by tGecko** [comment]
It's literally open source, read the code. 16/71 is nothing and the 16 positives are obvious false positives like "malware ai score" or "malicous: moderate confidence"

If you don't trust it, don't use it, simple as that.
