### ISSUE TITLE
FeatureRequest - Porofessor.gg search

### ISSUE THREAD

**Issue by cubedsphered** [tGecko/ChampSelectSpy#4]
I think U.GG is OK (fetches latest data semi-regularly),
OP.GG is _terrible_ (fetches last manual-update data, useless if they dont refresh their profiles regularly) but ... 
**Porofessor.gg always fetches the most recent data, without fail**, and with more stats displayed than the others. 
Here's standard URL, and specifiers explained (I tested them personally):
`https://porofessor.gg/pregame/euw/placeholder/soloqueue/season`

1. `euw` may be changed to any region accordingly.
2. `placeholder` is replaced by normal comma list of summoners (comma+space, e.g.: "A, B, C, D, E"). 
3. `/soloqueue` specifies games counted, can be replaced with `/ranked-only` for both solo and flex, or removed entirely for all games (normal + ranked)
4. `/season` is always at the end, can be removed to fetch only last 30 days of data (GREAT, since more recent data is more relevant)

I personally use `https://porofessor.gg/pregame/euw/placeholder/soloqueue`.
I'd suggest this specific one, with maybe the `/season` added if you desire. 
- _I paste over the `placeholder` bit._
- _`Soloqueue` is most relevant, since winrates inflate with premades, and normals/ARAMs are notoriously unreliable._
- _`Last 30 days (null)` is only the worse choice if player spaces out games (plays very rarely some months, intensely in others, or takes 3+ weeks' break)._
- _Region can be changed with your **dropdown menu**, as with U.GG and OP.GG._

P.S. These sites may remove pre-game pages entirely  due to less demand by players; IF this happens, coding to pull up the leagueofgraphs.com page for each listed profile will be good. Same advantage as with Porofessor, updates more regularly than u.gg or op.gg. 
P.P.S. If I knew coding, I'd do these changes myself, you've done plenty.
### Thanks for reading... Happy New Year! 🎉

**Comment by philipp-heller** [comment]
How is the status on this one? else I would try to implement it myself and send a merge after

**Comment by tGecko** [comment]
Feel free to submit a PR, i had this planned but life happened.

**Comment by matijuguera** [comment]
we could add it with chat gpt. I will take a look on it as soon as I have free time

**Comment by tGecko** [comment]
Implemented by @philipp-heller in [PR #6](https://github.com/tGecko/ChampSelectSpy/pull/6)
