### ISSUE TITLE
Implement SEA serves pls

### ISSUE THREAD

**Issue by itherbvb** [tGecko/ChampSelectSpy#5]
Hello Sir, I am from SEA (Singapore) Region. So RIOT SEA Servers just opened up yesterday. Hope you will add our server to your existing software.Thanks for your work.

**Comment by philipp-heller** [comment]
I have tried and implemented the SEA Area together with the Porofessor Patch on my Fork, ill link it here once I'm done with it

**Comment by tGecko** [comment]
@itherbvb  please try [version 1.5](https://github.com/tGecko/ChampSelectSpy/releases/tag/1.5)

**Comment by itherbvb** [comment]
> 

Thanks both of you.
